account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'account'

urlpatterns = [
    path('signup/', SignupView.as_view(), name= 'signup'),
    path('logout/', LogoutView, name= 'logout'),
    path('login/', auth_views.LoginView.as_view(), name= 'login'),
    # path('logout/', auth_views.LogoutView.as_view(), name= 'logout'),
]

pages/urls.py
from django.urls import path
from .views import *
app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('new_post/', CreatePostView.as_view(), name= 'new_post'),
    path('edit_post/<int:pk>', UpdatePostView.as_view(), name= 'update_post'),
    path('delete_post/<int:pk>', DeletePostView.as_view(), name= 'delete_post'),
]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('pages.urls', namespace='pages')),
]

account/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.user', on_delete=models.CASCADE, default=True)
    title = models.CharField(max_length=100)
    body = models.TextField()
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("pages:post_detail", args=[str(self.pk)])
    

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

app_name = 'account'

# Create your views here.
class SignupView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('account:login')

@login_required
def LogoutView(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('pages:home')

pages/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import *
# the app name
app_name = 'pages'

# Create your views here.

# CBVc
class HomePageView(ListView):
    model = Post
    template_name = 'pages/home.html'
    context_object_name = 'post'

class PostDetailView(DetailView):
    model = Post
    template_name = 'pages/detail.html'

class CreatePostView(CreateView):
    model = Post
    template_name = 'pages/add_post.html'
    fields = '__all__'

class UpdatePostView(UpdateView):
    model = Post
    template_name = 'pages/edit_post.html'
    fields = ['title', 'body']
    context_object_name = 'post'

class DeletePostView(DeleteView):
    model = Post
    template_name = 'pages/delete.html'
    context_object_name = 'post'
    success_url = reverse_lazy('pages:home')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
        <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    </head>
    
    <body>
        <nav>
            <h5 class="icon">RD_Blog</h5>
                <ul>
                    <li><a class="active" href="{% url 'pages:home' %}">Posts</a></li>
                    <li><a href="{% url 'pages:new_post' %}">+ New_Post</a></li>
                    <li><a href="">Contact</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'account:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'account:login' %}">Login</a></li>
                    {% endif %}
                </ul>
        </nav>
        {% block content %}
        
        {% endblock content %}
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    </body>
    </html>

templates/pages/add_post.html
{% extends "base.html" %}
{% block title %}
add_new_post
{% endblock title %}
{% block content %}
<div class="container">
    <h2 class="text-success">Add New Post</h2>
        <div class="col-lg-6 col-12 mx-auto pt-5">
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-success" type="submit" value="Post">
            </form>
        </div>
</div>
{% endblock content %}

templates/pages/delete.html
{% extends "base.html" %}
{% block title %}
delete_post
{% endblock title %}
{% block content %}
<div class="container">
    <h2 class="text-danger">Delete Post</h2>
        <div class="col-lg-6 col-12 mx-auto pt-5">
            <form action="" method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{post.title}}"</p>
                <input class="btn btn-success" type="submit" value="Confirm">
            </form>
        </div>
</div>
{% endblock content %}

templates/pages/detail.html
{% extends "base.html" %}
{% block title %}
post_detail_page
{% endblock title %}
{% block content %}
<div class="container">
    <h2 class="text-success text-capitalize">{{ post.title }}</h2>
    <p class="detail">{{ post.body }}</p>


    <hr>
    <a href="{% url 'pages:update_post' post.pk %}" class="text-success">Edit Post</a> | 
    <a href="{% url 'pages:delete_post' post.pk %}" class="text-success">Delete Post</a>
</div>
{% endblock content %}

templates/pages/edit_post.html
{% extends "base.html" %}
{% block title %}
edit_post
{% endblock title %}
{% block content %}
<div class="container">
    <h2 class="text-success">Edit Post</h2>
        <div class="col-lg-6 col-12 mx-auto pt-5">
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-success" type="submit" value="Update">
            </form>
        </div>
</div>
{% endblock content %}

templates/pages/home.html
{% extends "base.html" %}

{% block title%} home_page {% endblock%}
{% block content %}

<div class="container">
    <h2 class="text-success text-center">Post </h2>
    <br>
    <hr>
    {% if user.is_authenticated %}
    <p>Hi, <span class="text-success text-lowercase">{{user.username}}</span></p>
    {% else %}
    <p>You're not Login</p>
    <a href="{% url 'account:login' %}" class="text-success">Login</a> | 
    <a href="{% url 'account:signup' %}" class="text-success">Signup</a>
    <hr>
    {% endif %}
    <br>


    {% for p in post %}
    <h5><a href= "{% url 'pages:post_detail' p.pk %}" class="text-success">{{ p.title }}</a></h5>
    <p>{{ p.body }}<p>
        <br><br>
    {% endfor %}
</div>
{% endblock %}